# Generated by Django 2.1.1 on 2018-09-09 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20)),
                ('links', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='img')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('begin', models.DateTimeField(verbose_name='start date')),
                ('qrcode2', models.ImageField(upload_to='qrcode')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-mod_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'confirmation code',
                'verbose_name_plural': 'confirmation codes',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, unique=True)),
                ('c_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='avatar')),
                ('qrcode1', models.ImageField(upload_to='qrcode')),
                ('has_confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='groupconfirmstring',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Groups'),
        ),
        migrations.AddField(
            model_name='activities',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Groups'),
        ),
    ]
