# Generated by Django 2.1.1 on 2018-09-09 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_num', models.IntegerField(default=0)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activities')),
            ],
        ),
        migrations.CreateModel(
            name='LikeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_time', models.DateTimeField(auto_now_add=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='ParCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_num', models.IntegerField(default=0)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activities')),
            ],
        ),
        migrations.CreateModel(
            name='ParRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_time', models.DateTimeField(auto_now_add=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
